# Simulation Parameters
FPS = 30
GAME_SPEED = 1  # 1sec/1sec

# Field Parameters
SIZE_INCREASE_PER_PLAYER = 100
START_RADIUS = 5
START_MASS = 10
MAX_COLLECTIBLE_SPAWN_PER_UPDATE = 0.01 / FPS * GAME_SPEED  # per unit area
COLLECTIBLE_SIZE = 1
MAX_COLLECTIBLE_DENSITY = 0.01  # per unit area

# Cell Parameters
CELL_MOVE_SPEED = 1 * GAME_SPEED
CELL_SPLIT_SPEED = 2 * GAME_SPEED
CELL_MASS_DECAY_RATE = 1 - (0.002 / FPS * GAME_SPEED)
