# General Parameters
SCREEN_WIDTH = 900
SCREEN_HEIGHT = 900
MAXBOTS = 1000
MAXHUMANPLAYERS = 1

# Simulation Parameters
FPS = 30
GAME_SPEED = 1  # 1sec/1sec
SPEED_MODIFIER = FPS * GAME_SPEED

# Field Parameters
HASH_CELL_SIZE = 20
SIZE_INCREASE_PER_PLAYER = 50
START_RADIUS = 5
START_MASS = 10
MAX_COLLECTIBLE_DENSITY = 0.02  # per unit area

# Cell Parameters
BASE_MERGE_TIME = 10
CELL_MOVE_SPEED = 50 / SPEED_MODIFIER #units/sec
CELL_SPLIT_SPEED = 30 / SPEED_MODIFIER #units/sec
CELL_MASS_DECAY_RATE = 1 - (0.02 / SPEED_MODIFIER)

# Player Parameters:
MOMENTUM_PROPORTION_TO_MASS = 0.003
MOMENTUM_BASE = 6
